/*
import navbar from "../app/components/navbar";
import './globals.css'

export default function RootLayout({ children }) {
  return (

    
    <main className="">
      <head>
        <title>Promociones Ags.</title>
      </head>
      
        <header>
          <h1>Este es el inicio de sesion</h1>
          
        </header>
        {navbar()}
        {children}
    </main>
    
  );
}

*/

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
